# Generated by Django 4.0.6 on 2022-07-22 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bank_auth", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("type", models.CharField(max_length=30)),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, verbose_name="date joined"),
                ),
            ],
        ),
    ]
